### PR TITLE
Fixed issue getting tesla token on username and password login

### PR DESCRIPTION
**Pull request by evenmun**
Issue: #83

### CODE REVIEW

**Comment by bogosj** [comment]
I haven't used cmd/login in quite a while. When I run it with this PR I get the following:

go run . -o ~/tesla.token
Username: b****@gmail.com
Password: *********
✔ Passcode: 298871|

2023/05/19 01:30:36 verify: json decode: invalid character 'F' looking for beginning of value
exit status 1

**Comment by evenmun** [comment]
That's strange. I will look into that, but can you provide me with some more information? For example, can you debug and see what you get from the last request in the authentication process?

**Comment by bogosj** [comment]
I'm getting the following string:

"Found. Redirecting to /oauth2/v3/authorize/mfa/verify"

From this request:
https://github.com/bogosj/tesla/blob/main/auth.go#L233

**Comment by evenmun** [comment]
Hey :)
Are you able to test the changes again? 
The problem was the MFA verification request needed the _csrf token, and also, there was some issue decoding the MFA Verify response.

**Comment by bogosj** [comment]
Working now with MFA. Thanks for the contribution.

**Pull request merged**
