### PR TITLE
Migrate oauth2 functionality to the oauth2 library

### PR DESCRIPTION
**Pull request by michaelharo**

### CODE REVIEW

**Comment by andig** [comment]
@michaelharo you're basically rebuilding the uhthomas library but without the MFA part? Why not just use the OAuth config from there?

**Comment by andig** [comment]
Sorry, I was wrong. 

My idea was/is to make the authorisation stuff from https://github.com/uhthomas/tesla/blob/master/cmd/login/main.go as reusable as possible, including access to the oauth config. Currently that's not the case, discussion in https://github.com/uhthomas/tesla_exporter/issues/7#issuecomment-777197505. So instead of merging here I'd propose to work with uhthomas to provide a clean interface.

**Comment by michaelharo** [comment]
I think the login stuff should exist, but not be part of the NewClient interface as we each have different ways we want to provide login functionality, but once we have an oauth2 access/refresh token I assume everything else is common.

**Comment by andig** [comment]
I would like the ability to pass in an HTTP client that is configured for logging (instrumenting its roundtripper). Oauth does that by using the context, so and oauth client could handle authentication, token renewal and logging. The remaining pieces would be documentation how to create that client (using uhthomas) and and e2e example. That wouldn‘t need the oauth config to be part of this PR though?

**Comment by michaelharo** [comment]
As long as the context passed as part of NewClient has the http client associated in it then I think that meets your requirement.

**Comment by michaelharo** [comment]
@andig Do you have any additional concerns about this pull request?

**Comment by andig** [comment]
LGTM! Should we mention that injection a client can be done via the context as its not obvious?

**Comment by andig** [comment]
Fix #8

**Pull request merged**
