### PR TITLE
Add missing headers and user-name header rotation

### PR DESCRIPTION
**Pull request by andig**
This does not solve the current login issues but exposes the login request flow using a logging http client.

Note: might also make sense to only update the transport: https://github.com/uhthomas/tesla/compare/f00d0e07a2b61907751647920f5b7c1f8197c07a..1caf33b692d9258ef27505b335ee3aa8869c1e8d#diff-c52daedaeda258db15ec11d57bbf299412a20328f6cd026980ef07f01960dd3aR25

### CODE REVIEW

**Comment by andig** [comment]
Added all changes from @uhthomas. Can get the login and api call. My only test car right now replies with 408 to the actual api call, but that might be ok? Also noted, that the new transport MUST NOT be used for the login itself.

ping @uhthomas

**Comment by andig** [comment]
Fix #42

**Review by bogosj — APPROVED** [review]

**Comment by uhthomas** [comment]
Sorry for being so inactive the past couple weeks - lots going on!

The changes LGTM, thanks. I made a couple more upstream; like using base32 and ensuring the clients / contexts are passed around correctly. Should we merge them here?

I can confirm that the client works, albeit with _major_ rate limiting applied.

**Comment by andig** [comment]
> The changes LGTM, thanks. I made a couple more upstream; like using base32 and ensuring the clients / contexts are passed around correctly. Should we merge them here?

Yes please! It's your PR anyway- please feel free to amend or open new one.

Btw., do you intend to keep maintaining your repo or wouldn't it be easier to do all evolution here?

**Comment by andig** [comment]
ping @uhthomas seem we should get this closed before 1.0?

**Comment by andig** [comment]
@uhthomas I've merged your base32 changes but didn't take over returning the context as I didn't understand why that's needed.

**Comment by andig** [comment]
@bogosj  Rebased. Shall we get this in?

**Pull request merged**
